version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports: 
      - "27017:27017"
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mysql:
    container_name: mysql
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports: 
      - "3306:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  posgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgres/data

  redis:
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports: 
      - "5672:5672" 
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  mariadb:
    container_name: mariadb
    image: mariadb
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports: 
      - "3307:3306"
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  proxysql:
    container_name: proxysql
    image: proxysql/proxysql:2.0.15
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    ports:
      - "6032:6032"
      - "6033:6033"
    restart: always
    depends_on:
      - mariadb

volumes:
  mongodb:
  mongodb_config:
  mysql:
  mariadb:
  postgres:
  redis:
  rabbitmq:
  rabbitmq_log:
