version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports: ["27017:27017"]
    restart: always
    volumes: 
      - mongodb:/data/db
      - mongodb_config:/data/configdb


  mysql: 
    container_name: mysql
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports: ["3306:3306"]
    restart: always
    volumes: 
      - mysql:/var/lib/mysql


  posgresql: 
    container_name: postgres
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    restart: always
    volumes: 
      - postgres:/var/lib/postgres/data

volumes: 
    mongodb:
    mongodb_config:
    mysql:
    postgres: 

